{% set name = "cdtime" %}
{% set version = "3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cdat/cdtime/archive/V3.0.tar.gz
  sha256: fd7d47942a33b8ed9ef40a58430f7fc70f49bd86ace0e52f3fb4d4ea47a30c59

build:
  number: 0
  skip: True  # [win] 

requirements:
  build:
    - python
    - setuptools
    - libcdms
    - numpy 1.11*
    - cdat_info
    - libdrs_f
    - gcc
  run:
    - python
    - setuptools
    - libcdms
    - cdat_info
    - libdrs_f
    - numpy >=1.11

test:
  imports:
    - cdtime

about:
  home: http://uvcdat.llnl.gov/documentation/cdms/cdms_3.html
  license: 'CCLRC'
  license_file: 'LICENSE'
  summary: 'Climate calendar manipulation tools'
  description: |
      The cdtime module contains functions for converting between 
      these forms, based on the common calendars used in climate 
      simulation. Basic arithmetic and comparison operators are also available.
  dev_url: https://github.com/UV-CDAT/cdtime

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
