travis:
  secure:
    BINSTAR_TOKEN: QXWUMZc2/sK5Qsmkvcp5dfVYj8tc+bePr0BThwSnIQEV6ExZu0rN1PmB3r/9PGqJB2MrVTdKIiSrBsrk947WjlDGYEiqBII3SlY78JKdVkt+EKjMPei9EWBN43J8QJLUP5Qu9UdVjAVdmmWkPsZuSbQMkm23Widu6yizFeEuuKgMB+E7tG3pdrxd3sY5IGj3E9uLtVa7b9l7grxxgRoq5L60uj3kmd8MTT6e+CQAzScBsBWIOOwbzNdIFowi70eHpShXxVS0lpyqd1XyCPM3zmHEjt7+gI56Hxii1RJo6eNTlmELe7DbGSOvlkwSoSbWNHEqe20WokhOFS3OhOmHp2dQC+MW5oEPcDH9geXgd7QVGjsFBswA8nohVZQnDMX/rM26L1EZIL0AcZkrOPntKBfoWMalPa4R6z7omfZOAjbvVaFocbMzfscF41KjMqeQDwuuH1Xc5Muokg38IssC3ZR9KZQHRXjYc1DGvspr6XByHTWxhO2omE0zvHlL/iMZJEKS4ZK/UO3GggRrjzlOsW9InQ0iI0827EWEO7K1Azx8UHylOS1+/2gFUTIRspGO0cMu/tj51fdGfzMOr41C+dfPiSuibBz2/LPhwfXW3mlGrkkir6wZ5ofPhRlMgh7fVVwXM+E+Hmd3Zbj+XRJp2RiruCzYT/UvHlnvrj0PKl4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
